export * from './IconCheck'
export * from './IconLogo'
export * from './IconLogoShort'
export * from './IconCalendar'
export * from './IconTouch'
export * from './IconClose'
export * from './IconUpload'
export * from './IconViewMoreUp'
export * from './IconViewMoreDown'
export * from './IconPencil'
export * from './IconPapelera'
export * from './IconArrowUp'
export * from './IconArrowDown'
export * from './IconArrowRight'
export * from './IconArrowLeft'
export * from './IconAddButton'
export * from './IconRemoveButton'
export * from './IconSearch'
export * from './IconTableTwo'
export * from './IconTableFour'
export * from './IconTableSix'
export * from './IconTableHeight'

export * from './IconTikTok'
export * from './IconFacebook'
export * from './IconInstagram'

export * from './IconFood'
export * from './IconDefaultProduct'

export * from './IconHome'
export * from './IconStock'
export * from './IconStats'
export * from './IconSettings'
export * from './IconLogout'
export * from './IconMenu'

export * from './IconBars'
export * from './IconMapa'
export * from './IconMapaMobile'